#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8000/eureka
##      defaultZone: http://192.168.2.20:8761/eureka
##    register-with-eureka: false
##    fetch-registry: true
#  instance:
#    prefer-ip-address: true
