
#eureka配置只能放到这里,因为他是先加载的
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
#      defaultZone: http://192.168.2.20:8761/eureka
#    register-with-eureka: false
#    fetch-registry: false
  instance:
    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  application:
    name: config-server
  cloud:
    name: config-server
    config:
      server:
        #Git仓库信息
        git:
          basedir: D:/dev/gitRepositoryBase/config-server
          uri: git://localhost/java/springcloud/config-server.git
          search-paths: /**
      #分支
      label: master
      #访问git的账号
      username: fsmflying@163.com
      #访问git的密码
      password: fang1111ming
logging:
  level: debug